frase = 'Curso em video python'
print(frase)
print(frase[3])
print(frase[:14])
print(frase[13:])
print(frase[0:15])
print(frase[0:15:2])
print(frase.count('o'))
print(frase.upper())
print(len(frase))
print(frase.replace('python', 'android'))
print('Curso' in frase)
print(frase.split())
dividido = frase.split()
print(dividido[2])